romote:
  plat_path: 'E:\\test\\123'
  sql_path: 'D:\Company Works'
  web_path: 'D:\hundsun'

loacal:
  rar_path: 'D:\Download'

update_info:
  - ip: 10.31.116.66
    fsk_path: '112'
    dispatch_path: '234'

sftp_server:
  host: '192.168.102.185'
  port: 2022
  username: 'fxgl_fsk_read'
  password: '2r68F9fd'
  plat_path: '/PLAT/script/'
  fsk_path: '/FSK/script/'
  web_path: '/FSK/V202101.1.0/'